<?php
/**
 * @file
 * Code for the highlight feature.
 */

include_once 'compro_highlight.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function compro_highlight_entity_info_alter(&$entity_info) {
  if (isset($entity_info['highlight'])) {
    $entity_info['highlight']['label callback'] = 'compro_highlight_label';
  }
}

/**
 * Label callback.
 */
function compro_highlight_label($entity) {
  $output = 'Highlight entity';

  switch ($entity->bundle()) {
    case 'standard':
      if (isset($entity->field_highlight_headline['und'][0]['safe_value'])) {
        $output = $entity->field_highlight_headline['und'][0]['safe_value'];
      }
      break;
    
    case 'collection':
      if (isset($entity->field_highlight_collection_name['und'][0]['safe_value'])) {
        $output = $entity->field_highlight_collection_name['und'][0]['safe_value'];
      }
      break;
  }

  return $output;
}

/**
 * Implements hook_theme_registery_alter().
 */
function compro_highlight_theme_registry_alter(&$theme_registry) {
  // Defined path to current module.
  $module_path = drupal_get_path('module', 'compro_highlight');

  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}